### ISSUE TITLE
(New feature suggestion) Optical Proximity correction and a related quesition

### ISSUE THREAD

**Issue by Naluen** [heitzmann/gdstk#176]
Dear Author,

Would you be interested in add optical proximity correction (OPC) into your program?

![slide39-l](https://github.com/heitzmann/gdstk/assets/10174409/f113d4f9-2768-459c-ad4d-bc80ee6ff384)

I have tried to realize it on the level of usage by extending your class in Python. I learned a lot from the method "fillet". But I encounter a big problem: boolean operation "or" or "not" returned list instead of polygons, which makes it hard to operate furtherly.

Would you have any suggestion about how to get a pure polygon return from boolean operation?

Thank you very much.

**Comment by heitzmann** [comment]
It's not possible to have a single polygon as a result of a general boolean operation, because the operation can create a set of disjoint polygons. That said, most functions accept lists of polygons as inputs, where it makes sense. Otherwise, you should be processing each boolean output by itself in a loop.

Do you have any piece of code where you fond it difficult to operate on lists? Maybe I can help if you can share a concrete example.
